#!/usr/bin/env python
"""Vendor HOOPS-AI-tutorials' assembly_matcher.py into vendor/.

The assembly-to-assembly matching algorithm lives in the tutorials repository.
Rather than re-implementing it (and drifting from the reference), this tool
copies it verbatim under a generated header, the same approach
hoops_ai_native_bridge takes with assembly_matcher_py.h.

Usage
-----
    python tools/sync_assembly_matcher.py                 # copy + refresh header
    python tools/sync_assembly_matcher.py --check         # verify, no writes
    python tools/sync_assembly_matcher.py --source <path> # non-default location

``--check`` exits 1 when the vendored copy has drifted from the source, so it
can be wired into CI later.

The vendored file must never be hand-edited: fix the tutorial copy and re-sync.
"""

from __future__ import annotations

import argparse
import datetime
import hashlib
import pathlib
import sys
from typing import Optional

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = (
    REPO_ROOT.parent / "HOOPS-AI-tutorials" / "embeddings_pipeline" / "assembly_matcher.py"
)
VENDOR_PATH = REPO_ROOT / "vendor" / "assembly_matcher.py"

# Everything after this marker is a byte-for-byte copy of the source file, so
# --check can compare bodies without being confused by the header timestamp.
BODY_MARKER = "# --- vendored content below this line (do not edit) ---"

VENDOR_INIT = '''"""Third-party sources vendored verbatim.

Files in this package are generated by tools/ scripts and must not be
hand-edited. See tools/sync_assembly_matcher.py.
"""
'''


def sha256_text(text: str) -> str:
    """Hash the *normalised* text so CRLF and LF checkouts agree."""
    return hashlib.sha256(text.replace("\r\n", "\n").encode("utf-8")).hexdigest()


def build_header(source: pathlib.Path, digest: str, synced: str) -> str:
    try:
        shown_source = source.resolve().relative_to(REPO_ROOT.parent).as_posix()
    except ValueError:
        shown_source = source.resolve().as_posix()
    return (
        "# =========================================================================\n"
        "# VENDORED FILE -- DO NOT EDIT\n"
        "#\n"
        f"# Source : {shown_source}\n"
        f"# SHA-256: {digest}\n"
        f"# Synced : {synced}\n"
        "#\n"
        "# Regenerate: python tools/sync_assembly_matcher.py\n"
        "# Verify    : python tools/sync_assembly_matcher.py --check\n"
        "#\n"
        "# Fix the tutorial copy and re-run the sync tool; edits made here are\n"
        "# silently overwritten on the next sync.\n"
        "# =========================================================================\n"
        f"{BODY_MARKER}\n"
    )


def split_vendored(text: str) -> Optional[str]:
    """Return the body of a vendored file, or None when the marker is missing."""
    marker = text.find(BODY_MARKER)
    if marker < 0:
        return None
    return text[marker + len(BODY_MARKER):].lstrip("\r\n")


def read_source(source: pathlib.Path) -> str:
    if not source.is_file():
        sys.stderr.write(
            f"error: source not found: {source}\n"
            "Clone HOOPS-AI-tutorials next to this repository or pass --source.\n"
        )
        raise SystemExit(2)
    return source.read_text(encoding="utf-8")


def do_check(source: pathlib.Path) -> int:
    src_text = read_source(source)
    if not VENDOR_PATH.is_file():
        print(f"DRIFT: {VENDOR_PATH} is missing")
        return 1

    body = split_vendored(VENDOR_PATH.read_text(encoding="utf-8"))
    if body is None:
        print(f"DRIFT: {VENDOR_PATH} has no vendor header marker")
        return 1

    if sha256_text(body) != sha256_text(src_text):
        print("DRIFT: the vendored copy differs from the source")
        print(f"  source: {source}")
        print(f"  vendor: {VENDOR_PATH}")
        print("  run 'python tools/sync_assembly_matcher.py' to refresh")
        return 1

    print(f"OK: vendor/assembly_matcher.py matches {source}")
    return 0


def do_sync(source: pathlib.Path) -> int:
    src_text = read_source(source)
    digest = sha256_text(src_text)
    synced = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    VENDOR_PATH.parent.mkdir(parents=True, exist_ok=True)
    init_path = VENDOR_PATH.parent / "__init__.py"
    if not init_path.is_file():
        init_path.write_text(VENDOR_INIT, encoding="utf-8")

    VENDOR_PATH.write_text(build_header(source, digest, synced) + src_text, encoding="utf-8")
    print(f"synced {source}")
    print(f"    -> {VENDOR_PATH}")
    print(f"   sha256 {digest}")
    return 0


def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--source",
        type=pathlib.Path,
        default=DEFAULT_SOURCE,
        help=f"path to the upstream assembly_matcher.py (default: {DEFAULT_SOURCE})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the vendored copy without writing; exit 1 when it has drifted",
    )
    args = parser.parse_args(argv)
    return do_check(args.source) if args.check else do_sync(args.source)


if __name__ == "__main__":
    raise SystemExit(main())
